/**
 * Aggro launch suggestions built from the full Grand Archive card pool (all sets).
 * Counts target Standard constructed: Material ≤12 unique, Main ≥60 (max 4).
 */

function linesFromCounts(counts) {
  return counts.map(([quantity, name]) => `${quantity} ${name}`);
}

function formatSuggestionDeck({ name, blurb, material, main, sideboard = [] }) {
  return [
    `// ${name}`,
    `// ${blurb}`,
    "// Built with AdvGA from the full card pool (all sets)",
    "",
    "# Material Deck",
    "",
    ...material.map((cardName) => `1 ${cardName}`),
    "",
    "# Main Deck",
    "",
    ...linesFromCounts(main),
    "",
    "# Sideboard",
    "",
    ...linesFromCounts(sideboard),
    "",
  ].join("\n");
}

/** Fire Warrior aggro — Lorraine Blademaster / Ascendant Wings. */
export const FIRE_AGGRO_LORRAINE = formatSuggestionDeck({
  name: "Fire Aggro — Lorraine Blademaster",
  blurb: "Warrior · Fire · Discard fuel, champion attacks, Sword pressure",
  material: [
    "Spirit of Fire",
    "Lorraine, Wandering Warrior",
    "Lorraine, Blademaster",
    "Lorraine, Ascendant Wings",
    "Forgelight Blade",
    "Firetongue",
    "Dragon's Dawn",
    "Sword of Seeking",
    "Banner of Ares",
    "Revoker Bell",
    "Discharger",
    "Battery Core X",
  ],
  main: [
    [4, "Emberslash"],
    [4, "Stoked Slice"],
    [4, "Blistering Insurgent"],
    [4, "Package Courier"],
    [4, "Tindered Soldier"],
    [4, "Strapping Conscript"],
    [3, "Hasty Messenger"],
    [3, "Scars of Old"],
    [3, "Blazing Lunge"],
    [3, "Rending Flames"],
    [3, "Fiery Momentum"],
    [3, "Inflamed Bladehand"],
    [2, "Heated Vengeance"],
    [2, "Rampant Bladehand"],
    [2, "Outfitted Ravager"],
    [2, "Ritai Berserker"],
    [2, "Devastating Blow"],
    [2, "General at Arms"],
    [2, "Flamebound Draug"],
    [1, "Plutus, Fortune's Favor"],
    [1, "Molten Impact"],
    [1, "Flame Sweep"],
    [1, "Bill, Chimney Sweep"],
  ],
  sideboard: [
    [2, "Manic Zealot"],
    [2, "Indiscriminate Gyre"],
    [2, "Ash Filcher"],
    [2, "Wandering Glaivier"],
    [2, "Airship Captain"],
    [1, "Arthur, Young Heir"],
    [1, "Three of Hearts"],
    [1, "Two of Hearts"],
    [1, "Sword Saint of Everflame"],
    [1, "Ritai Berserker"],
  ],
});

/** Water Warrior aggro — Mordred Flawless / Aurelian Regent. */
export const WATER_AGGRO_MORDRED = formatSuggestionDeck({
  name: "Water Aggro — Mordred Flawless",
  blurb: "Warrior · Water · Deluge attacks, floating memory, relentless swings",
  material: [
    "Flawless Spirit of Mordred",
    "Mordred, Burnished Avenger",
    "Mordred, Flawless Blade",
    "Mordred, Aurelian Regent",
    "Eventide Spear",
    "Krustallan Longsword",
    "Mirrordepth's Blade",
    "AquaTech Blade X",
    "Arondight, Azure Blade",
    "Sword of Seeking",
    "Revoker Bell",
    "Discharger",
  ],
  main: [
    [4, "Soaked Slash"],
    [4, "Riptide Slash"],
    [4, "Floodborne Swing"],
    [4, "Drenching Finish"],
    [4, "Fountain Bladehand"],
    [4, "Evercurrent Raider"],
    [3, "Illusory Armsmaster"],
    [3, "Inundating Clash"],
    [3, "Skewering Advance"],
    [3, "Refreshing Slice"],
    [3, "Regulus Blitz"],
    [3, "Striking Tides"],
    [3, "Breakwater Cadet"],
    [2, "Floodborne Warrior"],
    [2, "Seafaring Mercenary"],
    [2, "Sword Saint of Eventide"],
    [2, "Halocline Scout"],
    [2, "Splashing Spearguard"],
    [1, "Dian Wei, Valorant Fury"],
    [1, "Xia Hou Dun, Gloryseeker"],
    [1, "Restorative Slash"],
    [1, "Weiss Knight"],
    [1, "Drifting Abysshell"],
  ],
  sideboard: [
    [2, "Restorative Slash"],
    [2, "Beguiling Bandit"],
    [2, "Powered Swordsman"],
    [2, "Floodward Sergeant"],
    [1, "Drifting Abysshell"],
    [1, "Hunt, Weiss King"],
    [1, "Benevolent Battle Priest"],
    [1, "Sunken Battle Priest"],
    [1, "Frostsworn Paladin"],
    [1, "Nanyue Portsman"],
    [1, "Weiss Knight"],
  ],
});

/** Wind Assassin aggro — Tristan Hired Blade / Shadowdancer. */
export const WIND_AGGRO_TRISTAN = formatSuggestionDeck({
  name: "Wind Aggro — Tristan Shadowdancer",
  blurb: "Assassin · Wind · Preparation counters, ambush allies, fast kills",
  material: [
    "Spirit of Wind",
    "Tristan, Underhanded",
    "Tristan, Hired Blade",
    "Tristan, Shadowdancer",
    "Zephyr's Edge",
    "Gearstride Gloves",
    "Windwalker Boots",
    "Ceremonial Stormblade",
    "Sundering Moon",
    "Sword of Seeking",
    "Revoker Bell",
    "Discharger",
  ],
  main: [
    [4, "Betraying Blade"],
    [4, "Combo Strike"],
    [4, "Fracturing Slash"],
    [4, "Poised Strike"],
    [4, "Cloaked Executioner"],
    [4, "Winbless Lookout"],
    [4, "Corhazi Outlook"],
    [3, "Turbulent Bounty Hunter"],
    [3, "Surveil the Winds"],
    [3, "Veiling Breeze"],
    [3, "Razorblade Execution"],
    [2, "Whirlwind Reaper"],
    [2, "Charged Assailant"],
    [2, "Shimmercloak Assassin"],
    [2, "Galewhisper Rogue"],
    [2, "Stifling Trap"],
    [2, "Arrow Trap"],
    [2, "Sirocco Operative"],
    [2, "Updraft Slice"],
    [2, "Expeditious Opening"],
    [1, "Bushwhack Bandit"],
    [1, "Parcenet, Royal Maid"],
  ],
  sideboard: [
    [2, "Blackmarket Broker"],
    [2, "Bushwhack Bandit"],
    [2, "Extortion Scheme"],
    [2, "Luster's Shroud"],
    [2, "Facet Together"],
    [1, "Ensnaring Fumes"],
    [1, "StrideTech W"],
    [1, "Galewhisper Rogue"],
    [1, "Whirlwind Reaper"],
    [1, "Charged Assailant"],
  ],
});

export const AGGRO_DECK_SUGGESTIONS = [
  {
    id: "fire-aggro",
    label: "Load Fire Aggro (Lorraine)",
    shortLabel: "Fire Aggro",
    description: "Warrior · Fire · Discard fuel, champion attacks, Sword pressure",
    listText: FIRE_AGGRO_LORRAINE,
    guideHref: "guides/aggro-fire-lorraine.html",
    guideLabel: "Fire aggro guide",
    element: "fire",
  },
  {
    id: "water-aggro",
    label: "Load Water Aggro (Mordred)",
    shortLabel: "Water Aggro",
    description: "Warrior · Water · Deluge attacks, floating memory, relentless swings",
    listText: WATER_AGGRO_MORDRED,
    guideHref: "guides/aggro-water-mordred.html",
    guideLabel: "Water aggro guide",
    element: "water",
  },
  {
    id: "wind-aggro",
    label: "Load Wind Aggro (Tristan)",
    shortLabel: "Wind Aggro",
    description: "Assassin · Wind · Preparation counters, ambush allies, fast kills",
    listText: WIND_AGGRO_TRISTAN,
    guideHref: "guides/aggro-wind-tristan.html",
    guideLabel: "Wind aggro guide",
    element: "wind",
  },
];
